description: An empty template for testing
pages:
  - type: top
    path: /
    sort: timestamp_utc desc
    blockSelector: .aggregation
    count: 20
  - path: /archive/
    blockSelector: .aggregation
    paginate: 20
