description: An empty template for testing
pages:
  - type: top
    path: /
    sort: timestamp_utc desc
    blockSelector: .aggregation
    count: 3

  - path: /archive/
    type: all
    blockSelector: .aggregation
    paginate: 20
